name: automate-react-s3

on:
 push:
   branches:
     - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setupnode
        uses: actions/setup-node@v2


      - run: yarn install
      - run: yarn build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      #- name: deploy static site to s3 bucket aws 
      #  run: aws s3 sync build/ s3://frontendbucket-s3

         
      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin 195747621510.dkr.ecr.ap-south-1.amazonaws.com       

      - name: Build, tag, and push image to Amazon ECR repogistry
    
      
        run: |
          docker build -t scsui:scsui .        
        
          docker tag scsui:scsui 195747621510.dkr.ecr.ap-south-1.amazonaws.com/helloworldpoc:scsui
              
          docker push 195747621510.dkr.ecr.ap-south-1.amazonaws.com/helloworldpoc:scsui

     
